// דגמים לפי סוג הרכב והיצרן. הרשימה מכסה את מה שנוסע בארץ היום ואת
// הדורות הקודמים שעדיין מגיעים למוסך — לא כל דגם שיוצר אי פעם בעולם.
// היא הצעה ולא כלוב: בטופס ובסינון אפשר להקליד דגם שאינו כאן.
const VEHICLE_MODELS = {
  car: {
    Toyota: ['Aygo', 'Yaris', 'Corolla', 'Auris', 'Avensis', 'Camry', 'Prius', 'Prius+', 'Verso', 'Supra', 'GR86', 'Mirai', 'Crown'],
    Hyundai: ['i10', 'i20', 'i25', 'i30', 'i40', 'Getz', 'Accent', 'Elantra', 'Sonata', 'Ioniq', 'Ioniq 6', 'Veloster', 'Grandeur'],
    Kia: ['Picanto', 'Rio', 'Ceed', 'ProCeed', 'Cerato', 'Forte', 'Optima', 'K5', 'Stinger', 'Niro', 'Soul', 'Carens'],
    Mazda: ['2', '3', '6', 'MX-5', 'RX-8', '323', '626', 'Premacy'],
    Skoda: ['Citigo', 'Fabia', 'Rapid', 'Scala', 'Octavia', 'Superb', 'Roomster'],
    Volkswagen: ['up!', 'Polo', 'Golf', 'Golf GTI', 'Jetta', 'Passat', 'Arteon', 'Beetle', 'Scirocco', 'Touran', 'Sharan', 'ID.3', 'ID.7'],
    Nissan: ['Micra', 'Note', 'Almera', 'Tiida', 'Sentra', 'Sunny', 'Pulsar', 'Primera', 'Maxima', 'Leaf'],
    Honda: ['Jazz', 'Civic', 'Accord', 'City', 'Insight', 'Legend', 'e'],
    Mitsubishi: ['Colt', 'Space Star', 'Mirage', 'Attrage', 'Lancer', 'Galant', 'i-MiEV'],
    Renault: ['Twingo', 'Clio', 'Megane', 'Fluence', 'Laguna', 'Talisman', 'Scenic', 'Espace', 'Zoe'],
    Peugeot: ['108', '208', '301', '308', '408', '508', 'RCZ', '206', '207'],
    'Citroën': ['C1', 'C3', 'C4', 'C5', 'C-Elysée', 'C4 Cactus', 'DS3', 'DS4', 'Xsara'],
    Seat: ['Mii', 'Ibiza', 'Leon', 'Toledo', 'Cordoba', 'Exeo', 'Altea'],
    Suzuki: ['Alto', 'Celerio', 'Swift', 'Baleno', 'Splash', 'Liana', 'SX4'],
    Ford: ['Ka', 'Fiesta', 'Focus', 'Mondeo', 'Fusion', 'Escort', 'Mustang', 'Galaxy', 'C-Max'],
    Chevrolet: ['Spark', 'Aveo', 'Sonic', 'Cruze', 'Malibu', 'Impala', 'Camaro', 'Corvette', 'Volt'],
    Opel: ['Karl', 'Adam', 'Corsa', 'Astra', 'Insignia', 'Vectra', 'Zafira', 'Meriva'],
    Fiat: ['500', '500e', 'Panda', 'Punto', 'Tipo', 'Bravo', 'Linea', 'Freemont'],
    BMW: ['סדרה 1', 'סדרה 2', 'סדרה 3', 'סדרה 4', 'סדרה 5', 'סדרה 6', 'סדרה 7', 'סדרה 8', 'i3', 'i4', 'i5', 'i7', 'Z4', 'M2', 'M3', 'M4', 'M5'],
    'Mercedes-Benz': ['A-Class', 'B-Class', 'C-Class', 'CLA', 'CLS', 'E-Class', 'S-Class', 'SLK', 'SLC', 'AMG GT', 'EQE', 'EQS'],
    Audi: ['A1', 'A3', 'A4', 'A5', 'A6', 'A7', 'A8', 'TT', 'R8', 'e-tron GT', 'RS3', 'S4'],
    Volvo: ['S40', 'S60', 'S80', 'S90', 'V40', 'V60', 'V90', 'C30'],
    Subaru: ['Impreza', 'Legacy', 'Levorg', 'WRX', 'BRZ', 'Justy'],
    Tesla: ['Model 3', 'Model S'],
  },
  suv: {
    Toyota: ['RAV4', 'C-HR', 'Corolla Cross', 'Yaris Cross', 'Highlander', 'Land Cruiser', 'Land Cruiser Prado', 'Fortuner', '4Runner', 'bZ4X'],
    Hyundai: ['Kona', 'Bayon', 'Tucson', 'ix35', 'Santa Fe', 'Creta', 'Palisade', 'Ioniq 5', 'Terracan', 'Galloper'],
    Kia: ['Stonic', 'Seltos', 'Sportage', 'Sorento', 'Niro', 'EV6', 'EV9', 'Xceed', 'Mohave'],
    Mitsubishi: ['ASX', 'Eclipse Cross', 'Outlander', 'Outlander PHEV', 'Pajero', 'Pajero Sport', 'Montero'],
    Jeep: ['Renegade', 'Avenger', 'Compass', 'Cherokee', 'Grand Cherokee', 'Wrangler', 'Gladiator', 'Commander'],
    'Land Rover': ['Defender', 'Discovery', 'Discovery Sport', 'Freelander', 'Range Rover', 'Range Rover Sport', 'Range Rover Evoque', 'Range Rover Velar'],
    Subaru: ['XV', 'Crosstrek', 'Forester', 'Outback', 'Ascent', 'Solterra', 'Tribeca'],
    Nissan: ['Juke', 'Qashqai', 'X-Trail', 'Murano', 'Pathfinder', 'Patrol', 'Terrano', 'Ariya'],
    Mazda: ['CX-3', 'CX-30', 'CX-5', 'CX-60', 'CX-9', 'MX-30', 'Tribute'],
    Skoda: ['Kamiq', 'Karoq', 'Kodiaq', 'Enyaq', 'Yeti'],
    Volkswagen: ['T-Cross', 'Taigo', 'T-Roc', 'Tiguan', 'Touareg', 'ID.4', 'ID.5', 'Atlas'],
    Ford: ['Puma', 'EcoSport', 'Kuga', 'Escape', 'Edge', 'Explorer', 'Bronco', 'Territory'],
    BMW: ['X1', 'X2', 'X3', 'X4', 'X5', 'X6', 'X7', 'iX', 'iX1', 'iX3'],
    'Mercedes-Benz': ['GLA', 'GLB', 'GLC', 'GLE', 'GLS', 'G-Class', 'ML', 'EQA', 'EQB', 'EQC'],
    Audi: ['Q2', 'Q3', 'Q4 e-tron', 'Q5', 'Q7', 'Q8', 'e-tron', 'SQ5'],
    Volvo: ['XC40', 'XC60', 'XC90', 'EX30', 'EX90', 'C40'],
    Suzuki: ['Ignis', 'Jimny', 'Vitara', 'Grand Vitara', 'S-Cross', 'Across', 'Samurai'],
  },
  van: {
    Ford: ['Transit', 'Transit Custom', 'Transit Connect', 'Transit Courier', 'Tourneo Connect', 'Tourneo Custom'],
    'Mercedes-Benz': ['Citan', 'Vito', 'Viano', 'V-Class', 'Sprinter', 'eVito', 'eSprinter'],
    Volkswagen: ['Caddy', 'Transporter T5', 'Transporter T6', 'Multivan', 'Crafter', 'ID.Buzz'],
    Renault: ['Kangoo', 'Express', 'Trafic', 'Master'],
    Peugeot: ['Partner', 'Rifter', 'Expert', 'Traveller', 'Boxer', 'Bipper'],
    'Citroën': ['Berlingo', 'Jumpy', 'SpaceTourer', 'Jumper', 'Nemo'],
    Fiat: ['Fiorino', 'Doblo', 'Scudo', 'Talento', 'Ducato'],
    Hyundai: ['H-1', 'H100', 'Porter', 'Staria'],
    Toyota: ['Proace', 'Proace City', 'HiAce', 'Dyna'],
    Nissan: ['NV200', 'NV300', 'NV400', 'Primastar', 'Interstar', 'Vanette'],
    Opel: ['Combo', 'Vivaro', 'Movano', 'Zafira Life'],
    Iveco: ['Daily'],
  },
  truck: {
    Volvo: ['FH', 'FH16', 'FM', 'FMX', 'FE', 'FL'],
    Scania: ['סדרה R', 'סדרה S', 'סדרה G', 'סדרה P', 'סדרה L', 'XT'],
    MAN: ['TGX', 'TGS', 'TGM', 'TGL', 'TGE'],
    DAF: ['XF', 'XG', 'XD', 'CF', 'LF'],
    Iveco: ['S-Way', 'Stralis', 'Eurocargo', 'Trakker', 'Daily'],
    'Mercedes-Benz': ['Actros', 'Arocs', 'Atego', 'Axor', 'Econic', 'Unimog', 'Atron'],
    'Renault Trucks': ['T', 'C', 'K', 'D', 'Midlum', 'Premium', 'Kerax'],
    Isuzu: ['N-Series', 'F-Series', 'Forward', 'Giga', 'D-Max'],
    Hino: ['300', '500', '700'],
    Tata: ['LPT', 'Prima', 'Ultra', 'Xenon'],
  },
  bus: {
    'Mercedes-Benz': ['Sprinter City', 'Tourismo', 'Citaro', 'Travego', 'Intouro'],
    MAN: ["Lion's Coach", "Lion's City", "Lion's Intercity", 'TGE Minibus'],
    Volvo: ['9700', '9900', '7900', 'B8R', 'B11R'],
    Scania: ['Touring', 'Interlink', 'Citywide', 'Irizar i6'],
    Iveco: ['Crossway', 'Evadys', 'Daily Minibus', 'Urbanway'],
    Setra: ['S 415', 'S 416', 'S 431 DT', 'MultiClass', 'ComfortClass'],
    Higer: ['KLQ6109', 'KLQ6119', 'H-Series', 'Azure'],
    'Golden Dragon': ['XML6957', 'Navigator', 'Triumph', 'City Bus'],
    Otokar: ['Vectio', 'Sultan', 'Kent', 'Navigo', 'Territo'],
  },
  moto: {
    Honda: ['CB500', 'CB650R', 'CBR600RR', 'CBR1000RR', 'CRF300L', 'Africa Twin', 'NC750X', 'Forza 350', 'PCX 125', 'SH150', 'Rebel 500'],
    Yamaha: ['MT-07', 'MT-09', 'MT-03', 'YZF-R1', 'YZF-R7', 'Tracer 9', 'Tenere 700', 'TMAX', 'XMAX 300', 'NMAX 155', 'Bolt'],
    Suzuki: ['GSX-R600', 'GSX-R1000', 'GSX-S750', 'SV650', 'V-Strom 650', 'V-Strom 1050', 'Burgman 400', 'Address 125'],
    Kawasaki: ['Ninja 400', 'Ninja 650', 'Ninja ZX-6R', 'Ninja ZX-10R', 'Z650', 'Z900', 'Versys 650', 'Vulcan S', 'W800'],
    BMW: ['R 1250 GS', 'R 1300 GS', 'F 900 R', 'F 850 GS', 'S 1000 RR', 'S 1000 XR', 'C 400 GT', 'G 310 R'],
    KTM: ['Duke 125', 'Duke 390', 'Duke 790', 'Duke 890', 'RC 390', '390 Adventure', '890 Adventure', '1290 Super Duke'],
    Ducati: ['Monster', 'Panigale V2', 'Panigale V4', 'Multistrada V4', 'Scrambler', 'Diavel', 'Streetfighter'],
    Piaggio: ['Liberty 125', 'Medley 150', 'Beverly 300', 'Beverly 400', 'MP3 400', 'Zip'],
    Vespa: ['Primavera 125', 'Sprint 150', 'GTS 300', 'GTV', 'Elettrica'],
    SYM: ['Jet 14', 'Symphony ST', 'Cruisym 300', 'Maxsym TL', 'Fiddle', 'Joymax'],
    Kymco: ['Agility 125', 'People S 125', 'Like 150', 'Downtown 350', 'Xciting 400', 'AK 550'],
    Aprilia: ['RS 660', 'RS4 125', 'Tuono 660', 'Tuono V4', 'SR GT 200', 'SXR 160'],
    'Harley-Davidson': ['Sportster S', 'Iron 883', 'Softail Standard', 'Fat Boy', 'Street Glide', 'Road King', 'Pan America'],
  },
  atv: {
    Polaris: ['Sportsman 570', 'Sportsman 850', 'Sportsman XP 1000', 'RZR 1000', 'RZR Turbo', 'Ranger 1000', 'Scrambler'],
    'Can-Am': ['Outlander 570', 'Outlander 1000', 'Renegade 1000', 'Maverick X3', 'Maverick Sport', 'Defender HD10'],
    CFMoto: ['CForce 450', 'CForce 625', 'CForce 1000', 'UForce 1000', 'ZForce 950', 'UForce 600'],
    Yamaha: ['Grizzly 700', 'Kodiak 700', 'Raptor 700', 'Wolverine RMAX', 'YFZ450R'],
    Honda: ['TRX 420', 'TRX 520', 'TRX 700XX', 'Pioneer 700', 'Pioneer 1000', 'Talon 1000'],
    Kawasaki: ['Brute Force 750', 'KFX 450R', 'Mule Pro-FXT', 'Teryx KRX 1000'],
    Segway: ['Snarler AT6', 'Fugleman UT10', 'Villain SX10', 'Snarler AT5'],
    Linhai: ['300', '400', '500', '570', 'M550L'],
  },
  tractor: {
    'John Deere': ['5050', 'סדרה 5M', 'סדרה 6M', 'סדרה 6R', 'סדרה 7R', 'סדרה 8R', 'סדרה 9R'],
    'New Holland': ['T4', 'T5', 'T6', 'T7', 'T8', 'TD', 'TL'],
    'Massey Ferguson': ['MF 3700', 'MF 4700', 'MF 5700', 'MF 6700', 'MF 7700', 'MF 8700'],
    Kubota: ['סדרה B', 'סדרה L', 'סדרה M', 'MK', 'M7'],
    'Case IH': ['Farmall', 'Maxxum', 'Puma', 'Magnum', 'Optum', 'Quadtrac'],
    'Deutz-Fahr': ['סדרה 5', 'סדרה 6', 'סדרה 7', 'Agrotron', 'Agrofarm'],
    Landini: ['Rex', 'Rex 4', 'Serie 4', 'Powerfarm', 'Landpower'],
    Valtra: ['סדרה A', 'סדרה G', 'סדרה N', 'סדרה T', 'סדרה S'],
    Claas: ['Atos', 'Arion', 'Axion', 'Xerion', 'Nexos'],
  },
  forklift: {
    Toyota: ['8FG', '8FD', '8FBE', 'Traigo 24', 'Traigo 48', 'Tonero'],
    Linde: ['H20', 'H25', 'H30', 'E16', 'E20', 'R14', 'R16'],
    Hyster: ['H2.5FT', 'H3.0FT', 'J2.5XN', 'Fortens', 'Reach Truck'],
    Still: ['RX 20', 'RX 60', 'RX 70', 'EXV', 'FM-X', 'EXU'],
    Jungheinrich: ['EFG 216', 'EFG 320', 'ETV 216', 'ETV 320', 'TFG 316', 'EJE'],
    Caterpillar: ['DP25', 'DP30', 'EP16', 'EP20', 'GP25', 'NR16'],
    Komatsu: ['FG15', 'FG25', 'FD25', 'FD30', 'BX50', 'AE50'],
    Doosan: ['D25S', 'D30S', 'G25P', 'B20X', 'B30X', 'BR14'],
  },
};

// דגמים לסוג ויצרן. מחזיר רשימה ריקה כשאין — הממשק פשוט יבקש להקליד.
function modelsFor(kind, make) {
  const byMake = VEHICLE_MODELS[kind];
  return (byMake && byMake[make]) ? byMake[make] : [];
}

module.exports = { VEHICLE_MODELS, modelsFor };
